CREATE TABLE Enlaces(
idEnlaces INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
URL VARCHAR(500) NOT NULL
);

CREATE TABLE Item(
idItem INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR(100) NOT NULL,
contenido VARCHAR(500) NOT NULL,
portada VARCHAR(500) NOT NULL,
tipo VARCHAR(100) NOT NULL,
trailer VARCHAR(500) NOT NULL,
año INTEGER NOT NULL,
fkEnlaces INTEGER NOT NULL,
CONSTRAINT FOREIGN KEY (fkEnlaces) REFERENCES Enlaces(idEnlaces)
);

CREATE TABLE Usuario(
idUsuario INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
nickname VARCHAR(100) NOT NULL,
contrasenia VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL
);

CREATE TABLE Comentarios(
idComentarios INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
cuerpo VARCHAR(500) NOT NULL,
fecha DATE NOT NULL,
puntuacion INTEGER NOT NULL,
fkUsuario INTEGER NOT NULL,
CONSTRAINT FOREIGN KEY (fkUsuario) REFERENCES Usuario(idUsuario),
fkItem INTEGER NOT NULL,
CONSTRAINT FOREIGN KEY (fkItem) REFERENCES Item(idItem)
);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Shingeki no kyojin","Muchos años atrás, la humanidad estuvo al borde de la extinción con la aparición de unas criaturas gigantes que devoraban a todas las personas. Huyendo, la humanidad consiguió sobrevivir en una ciudad fortificada de altas murallas que se ha convertido en el último reducto de la civilización contra los Titanes que campan a sus anchas por el mundo. Ahora esa paz está a punto de verse interrumpida por una cadena de acontecimientos que llevará a desvelar qué son los Titanes y cómo aparecieron","https://i.imgur.com/f6Djwi5.jpg","serie","https://www.youtube.com/watch?v=FRn6xXXF-7s","2013,%Y",4);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("WandaVision","Tres semanas después del final de Avengers: Endgame (2019),4​ Wanda Maximoff y Visión están viviendo una vida de ensueño en las afueras, en la pequeña ciudad de Westview (Nueva Jersey), mientras tratan de ocultar sus poderes. Pero a medida que pasan por nuevas décadas y cambian de escenarios televisivos, la pareja empieza a sospechar que algo no va bien.","https://i.imgur.com/jlsDljS.jpg","serie","https://www.youtube.com/watch?v=sj9J2ecsSpo","2021,%Y",2);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("The Boys","The Boys está ambientada en un universo en el que los individuos superpoderosos son reconocidos como héroes por el público en general y trabajan para la poderosa corporación Vought International, que los comercializa y monetiza. Fuera de sus personajes heroicos, la mayoría son arrogantes y corruptos. La serie se centra principalmente en dos grupos: los Siete, el principal equipo de superhéroes de Vought International, y The Boys, los titulares, vigilantes que buscan derribar a Vought y a los superhéroes corruptos.","https://i.imgur.com/8ew8NDy.jpg","serie","https://www.youtube.com/watch?v=eshJeoaDmtY","2019,%Y",3);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Invencible","Mark Grayson es un adolescente normal, excepto por el hecho de que su padre, Nolan, es el superhéroe más fuerte del planeta. Poco después de su decimoséptimo cumpleaños, Mark comienza a desarrollar sus propios poderes y entra en la tutela de su padre. A medida que Mark utiliza sus poderes para el bien, descubre que el legado de su padre puede no ser tan heroico como parece.","https://i.imgur.com/sCsz4Yd.jpg","serie","https://www.youtube.com/watch?v=ROCIksHW2oc","2021,%Y",3);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Jujutsu kaisen","Dificultades, arrepentimiento, vergüenza… Los sentimientos negativos de los humanos se convierten en Maldiciones que nos acechan en nuestra vida diaria. Las Maldiciones campan a sus anchas por todo el mundo, y pueden llevar a las personas a sufrir terribles desgracias e incluso dirigirlas a su muerte. Y lo que es peor: solo una Maldición puede exorcizar otra Maldición.","https://i.imgur.com/TqlkEou.jpg","serie","https://www.youtube.com/watch?v=pkKu9hLT-t8","2020,%Y",4);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Peaky blinders","1919. Inglaterra. Thomas Shelby lidera una conocida banda de Birmingham que avanza con ferocidad por el bajo mundo.","https://i.imgur.com/xQuTcOW.jpg","serie","https://www.youtube.com/watch?v=H282c9q2MUU","2013,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Extracurricular","La doble vida de un estudiante modelo que acaba de sumergirse en el mundo del crimen da un giro cuando una compañera de clase se interesa en su secreto.","https://i.imgur.com/yaaOPhi.jpg","serie","https://www.youtube.com/watch?v=cdjQak1Roc0","2020,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("locke & key","Tras el asesinato de su padre, tres hermanos se mudan con su madre al hogar donde él creció: una mansión repleta de llaves mágicas que guardan poderes y secretos.","https://i.imgur.com/2QvqAgi.jpg","serie","https://www.youtube.com/watch?v=iSzi100tz5M","2020,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("The killing","Los detectives de homicidios Sarah Linden y Stephen Holder se involucran más de lo debido en todos los crímenes que intentan resolver en esta serie aclamada por la crítica.","https://i.imgur.com/XcXgjzP.jpg","serie","https://www.youtube.com/watch?v=OkbfvPeH3G0&t=25s","2011,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Bojack Horseman","Conoce al caballo más querido de los noventa, pero 20 años después. Un cascarrabias con un corazón no precisamente de oro, ¿quizás de cobre?","https://i.imgur.com/lJVwPyj.jpg","serie","https://www.youtube.com/watch?v=zpTZg9AHxnw","2014,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Hilda","La valiente Hilda deja el bosque encantado para ir a la ciudad y encuentra nuevos amigos, aventuras y criaturas mágicas.","https://i.imgur.com/2HEAqI4.jpg","serie","https://www.youtube.com/watch?v=oawTkOjbDQw","2018,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("This is us","La historia de la familia Pearson comienza en 1979, cuando los trillizos de Jack y Rebecca llegan a la familia de una manera inesperada. Una saga emotiva sobre el amor, la vida y la derrota que se desenvuelve durante varias generaciones.","https://i.imgur.com/kEkF0PL.jpg","serie","https://www.youtube.com/watch?v=OkTEQwsE8l4","2016,%Y",3);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("¿Quién mató a Sara?","Resuelto a hacer venganza y demostrar que lo incriminaron en la muerte de su hermana, Álex se dispone a sacar a la luz mucho más que al verdadero autor del asesinato.","https://i.imgur.com/Oo1AAqZ.jpg","serie","https://www.youtube.com/watch?v=tyU4zz_ds-s","2021,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Queer Eye","¡Prepara los pañuelos descartables! Esta temporada, los Fab 5 te traen consejos únicos, emotivas transformaciones y revelaciones que te dejarán lagrimeando.","https://i.imgur.com/q1wyeqK.jpg","serie","https://www.youtube.com/watch?v=GZMrivD2Aok","2018,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Glow up","En esta competencia, un grupo de aspirantes a maquilladores se esmeran por superar coloridos retos y ganar su gran oportunidad profesional en la industria de la belleza.","https://i.imgur.com/qlxS9jK.jpg","serie","https://www.youtube.com/watch?v=Boq57jg7v4Q","2019,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("¡Santo golpe!","A un pueblo de Chiapas llegan dos individuos sin escrúpulos que roban al santo del templo. Los pobladores los persiguen a través de la región para recuperar lo que les arrebataron. Dominique Jonard realizó este cortometraje junto con varios niños de Zinacantán, un pueblo tzotzil de los Altos de Chiapas.","https://i.imgur.com/9EUNlkf.jpg","cortometraje","https://www.youtube.com/watch?v=7gLu9nMdaEY","1997,%Y",5);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("La bestia","Un joven contrabandista mexicano y una niña viajan ilegalmente en lo alto de un tren de carga, llamado La Bestia para llegar a Estados Unidos. Una lesión transforma su percepción del viaje.","https://i.imgur.com/L39k0gA.jpg","cortometraje","https://www.youtube.com/watch?v=isEFmtCncdg&t=13s","2020,%Y",5);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Amor, nuestra prisión","Documental animado que retrata por medio de varias técnicas visuales la naturaleza de las relaciones amorosas dentro del penal de Atlacholoaya, Morelos. Esta obra audiovisual es narrada por las voces de mujeres privadas de su libertad, obligadas a buscar una alternativa a la soledad.","https://i.imgur.com/wYU1xVW.jpg","cortometraje","https://www.youtube.com/watch?v=R6g_wkyzHr4","2016,%Y",5);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Aya","Entre paisajes psicosomáticos, Juan un niño de los Andes peruanos, hará lo imposible por cumplir el último deseo de su madre así tenga que alejarse de sus propias enseñanzas.","https://i.imgur.com/7JfkihS.jpg","cortometraje","https://www.youtube.com/watch?v=CKJuypCZr9Q&t=7s","2016,%Y",5);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Xpectativa","Un espacio desconocido, un hombre sin identidad y una situación extraña. El descubrimiento, la presión, la culpa y la liberación.Un espacio desconocido, un hombre sin identidad y una situación extraña. El descubrimiento, la presión, la culpa y la liberación.","https://i.imgur.com/O0fTnpy.jpg","cortometraje","https://www.youtube.com/watch?v=6Iv7tA6Hj6E","2005,%Y",5);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Hora de viajar!","Este cortometraje combina animación tradicional en blanco y negro y animación por computadora.4​5​ El corto cuenta con los personajes de Walt Disney de finales de la década de 1920, y cuenta con grabaciones de archivo de Walt Disney como la voz de Mickey Mouse.","https://i.imgur.com/MiuiO5K.jpg","cortometraje","https://www.youtube.com/watch?v=VIsuaDajIjg","2013,%Y",2);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Cabeza o Corazón","Esta es la historia de la pelea entre el cerebro y el corazón de Paul. El cerebro pragmático, lógico,calculador. Su corazón es de espíritu libre, aventurero, ansioso de ser libre. Divididos entre la rutina de la vida laboral y el deseo de divertirse en la playa, mente y corazón finalmente lograrán un acuerdo y permitirán que Paul viva una vida más equilibrada.","https://i.imgur.com/bTn0Hrw.jpg","cortometraje","https://www.youtube.com/watch?v=AoxIJXChMkY","2016,%Y",2);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Hair love ","Zuri, de siete años, intenta peinar su cabello grueso y natural mientras ve un video instructivo narrado por su madre . Su padre, Stephen, intenta ayudarla y, después de mucho esfuerzo, logra peinarla. Luego, Zuri le muestra a su papá el video de su mamá peinándose, donde él pudo hacer lo mismo.","https://i.imgur.com/DmuHAX6.jpg","cortometraje","https://www.youtube.com/watch?v=mBzzIvkyq50","2019,%Y",6);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Room 8","Este Cortometraje fue premiado con el Bafta, los premios de la academia británica de cine, como mejor cortometraje en el año 2014. Se trata de un cortometraje con ciertas reminiscencias a los cuentos de Borges que nos presenta un insólito relato lleno de simbolismo y con una forma genial de provocar la reflexión, eso sí, siempre manteniéndonos totalmente sumergidos ante lo extraordinario de los acontecimientos. He de decir que este cortometraje es uno de mis favoritos y un ejemplo perfecto de cómo hay historias que deben ser contadas dentro del formato del cortometraje.","https://i.imgur.com/r7JWgSB.jpg","cortometraje","https://www.youtube.com/watch?v=jeEWgOLQZcE","2013,%Y",6);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Paperman","Ambientado en Nueva York en los años 40 nos cuenta la historia de un joven que se esfuerza por alcanzar a una chica que ha conocido en la estación de tren y de la cual se ha enamorado. Paperman es un cortometraje mudo en el que se combinan elementos de la animación tradicional y la animación por computadora. Todo una maravilla de la técnica al servicio de la narración.","https://i.imgur.com/MbVRrU5.jpg","cortometraje","https://www.youtube.com/watch?v=mM6cLnscmO8","2012,%Y",2);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Si algo me pasa, los quiero","Después de un trágico tiroteo escolar, una pareja en duelo intenta procesar el vacío emocional que le dejó la muerte de su hija.","https://i.imgur.com/MRGpc99.jpg","cortometraje","https://www.youtube.com/watch?v=s3jQfcXp0OA","2020,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Sitara: Que las niñas sueñen por fin","Corto mudo ambientado en el Pakistán de los 70 sobre una adolescente que sueña con ser piloto sin saber que el padre la casará con un hombre mayor.","https://i.imgur.com/d1iWCrW.jpg","cortometraje","https://www.youtube.com/watch?v=0zeYA8uTRKs","2020,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("La abuela grillo","La abuela grillo forma parte de la mitología del pueblo indígena Ayoreo de Bolivia. Es la dueña de la lluvia y por medio de su canto lograr reverdecer los lugares donde está. Pero algunas veces provoca inundaciones que perjudican y por ello es echada de la comunidad. Cuando llega a la ciudad es capturada y obligada a cantar para que unos villanos lucren con el agua que es un derecho humano para todos.","https://i.imgur.com/4wkTsXr.jpg","cortometraje","https://www.youtube.com/watch?v=M1CoOF7WUP8","2009,%Y",5);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Whiplash","El objetivo de Andrew Neiman (Miles Teller), un joven y ambicioso baterista de jazz, es triunfar en el elitista Conservatorio de Música de la Costa Este. Marcado por el fracaso de la carrera literaria de su padre, Andrew alberga sueños de grandeza. Terence Fletcher (J.K. Simmons), un profesor conocido tanto por su talento como por sus rigurosos métodos de enseñanza, dirige el mejor conjunto de jazz del Conservatorio. Cuando Fletcher elige a Andrew para formar parte del grupo, la vida del joven cambiará.","https://i.imgur.com/a8HSUp7.jpg","pelicula","https://www.youtube.com/watch?v=7d_jQycdQGo","2014,%Y",3);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Wolfwalkers","En una época en la que reinan la superstición y la magia, los lobos están considerados como una fuerza demoníaca que debe ser eliminada. Robyn es una joven aprendiz que viaja hasta Irlanda junto a su padre para erradicar al último grupo de lobeznos que conoce, pero la situación cambia cuando Robyn salva a Mebh. Su amistad la lleva a conocer el mundo de los denominados Wolfwalkers, transformándose en aquello que su padre la ha mandado a destruir.","https://i.imgur.com/jsKdweT.jpg","pelicula","https://www.youtube.com/watch?v=d_Z_tybgPgg","2020,%Y",7);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Mean Girls","Recién entrando a la prepa, una adolescente entabla amistad con tres populares, pero también manipuladoras estudiantes.","https://i.imgur.com/SNoSzHm.jpg","pelicula","https://www.youtube.com/watch?v=oDU84nmSDZY&t=49s","2004,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Mi vida a los diecisiete","Cuando la mejor (y única) amiga de Nadine comienza a salir con su odiado hermano mayor, la cínica vida de la adolescente se vuelve todavía más insoportable","https://i.imgur.com/UKSiawK.jpg","pelicula","https://www.youtube.com/watch?v=Lza1bXCNQak","2016,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("John Wick","John Wick es un asesino a sueldo retirado que vuelve a la acción después de que un jefe mafioso haya puesto precio a su cabeza y le haya robado todo lo que le quedaba tras la muerte de su esposa.","https://i.imgur.com/ZevdNZq.jpg","pelicula","https://www.youtube.com/watch?v=BzLA7Ey2Af4","2014,%Y",3);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Kill Bill: Volume 1","Una asesina despierta de un coma y, tras descubrir que el hijo que llevaba en el vientre ya no está, decide salir a buscar a los criminales que la traicionaron.","https://i.imgur.com/XFNYoz5.jpg","pelicula","https://www.youtube.com/watch?v=w75pIkF6EQo","2003,%Y",3);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Dumplin","La película sigue la historia de la texana Willowdean , cuya madre es una exreina de belleza que se encuentra organizando audiciones para el certamen próximo. Dumplin', apodo dado por su madre, es una joven obesa que retando a su madre, decide inscribirse en el concurso como forma de protesta contra el sistema. Lo que no se imagina, es que incentivará a otras jóvenes diferentes al estereotipo de belleza a apoyar su causa.","https://i.imgur.com/IEXPpWJ.jpg","pelicula","https://www.youtube.com/watch?v=qsjEmKVgnlw","2018,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("La Familia Mitchell vs. Las Máquinas","El viaje por carretera de la familia Mitchell, que va a acompañar a uno de sus hijos a su primer día de universidad, se ve interrumpido por una insurrección tecnológica que amenaza a la humanidad.","https://i.imgur.com/d5VYPnr.jpg","pelicula","https://www.youtube.com/watch?v=cMLcCLglGoQ","2021,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Spider-Man: Un nuevo universo","Luego de ser mordido por una araña radioactiva, el joven Miles Morales desarrolla misteriosos poderes que lo transforman en el Hombre Araña. Ahora deberá usar sus nuevas habilidades ante el malvado Kingpin, un enorme demente que puede abrir portales hacia otros universos.","https://i.imgur.com/no69FXn.jpg","pelicula","https://www.youtube.com/watch?v=8OG1kMD7suQ","2018,%Y",3);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Shrek 2","En esta ocasión, Shrek debe enfrentarse al mayor de los problemas que se podía imaginar: conocer a sus suegros.","https://i.imgur.com/wXOX3PD.jpg","pelicula","https://www.youtube.com/watch?v=VbJG3BVFrJ8","2004,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Raya y el último dragón","Raya, una guerrera solitaria, debe localizar a un dragón legendario para restaurar su tierra fracturada y a su gente dividida.","https://i.imgur.com/iPnmCPk.jpg","pelicula","https://www.youtube.com/watch?v=l4QQS2gNmPc","2021,%Y",2);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("¡Huye!","Chris va a conocer a los padres de Rose, su novia. Al principio se muestran encantadores, si bien un tanto nerviosos. Chris supone que se debe a que él es negro, pero un poco más tarde descubre que sus suegros ocultan un secreto espeluznante.","https://i.imgur.com/TDRtdEH.jpg","pelicula","https://www.youtube.com/watch?v=HOtVOxS7SjA","2017,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Se7en","Somerset es un solitario y veterano detective a punto de retirarse que se encuentra con Mills, un joven impulsivo. Ambos investigan un particular asesinato. Es este el primero de una serie de crímenes que aluden los siete pecados capitales.","https://i.imgur.com/uWnWWY0.jpg","pelicula","https://www.youtube.com/watch?v=UenSg2kQtio","1995,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Malcolm & Marie","Cuando un cineasta y su novia regresan a casa después del estreno de su película, tensiones acumuladas y revelaciones dolorosas los llevan a redefinir su relación.","https://i.imgur.com/P38vHUj.jpg","pelicula","https://www.youtube.com/watch?v=4hPC4Wee_oY","2021,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Misterio a bordo","Durante un muy esperado viaje a Europa, un policía de Nueva York y su esposa tratan de resolver un misterioso asesinato a bordo del yate de un multimillonario.","https://i.imgur.com/JJDXWPD.jpg","pelicula","https://www.youtube.com/watch?v=R8HZeYfJnNU","2019,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Loco por ella","Después de pasar una alocada noche con Carla, Adri descubre que hay una sola manera de volver a verla: internarse en el centro psiquiátrico donde vive ella.","https://i.imgur.com/Urzysym.jpg","pelicula","https://www.youtube.com/watch?v=TvfIZU34is4","2021,%Y",1);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Sylvie's Love","Sylvie tiene un romance de verano con un saxofonista que consigue un trabajo en la tienda de discos de su padre en Harlem. Cuando se vuelven a conectar años después, descubren que sus sentimientos mutuos no se han desvanecido con los años.","https://i.imgur.com/E4YpyML.jpg","pelicula","https://www.youtube.com/watch?v=SbjakuJZgww","2020,%Y",3);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("Soul","Un profesor de música que ha perdido la pasión se transporta fuera de su cuerpo al Gran Antes y debe encontrar el camino de regreso con la ayuda de un alma infantil que aprende sobre sí misma.","https://i.imgur.com/hJoA301.jpg","pelicula","https://www.youtube.com/watch?v=RFAjF3z8row","2020,%Y",2);
INSERT INTO item(titulo,contenido,portada,tipo,trailer,año,fkEnlaces)VALUES("¡Hoy sí!","Unos padres que usualmente dicen que no a todo deciden ceder el control a sus hijos por un día, con algunas condiciones, y desatan un sinfín de divertidas aventuras.","https://i.imgur.com/44GaHzH.jpg","pelicula","https://www.youtube.com/watch?v=QWJX0u1Fa9U","2021,%Y",1);
INSERT INTO enlaces(URL)VALUES("https://www.netflix.com/co/");
INSERT INTO enlaces(URL)VALUES("https://www.disneyplus.com/es-co");
INSERT INTO enlaces(URL)VALUES("https://www.primevideo.com/");
INSERT INTO enlaces(URL)VALUES("https://www.crunchyroll.com/es");
INSERT INTO enlaces(URL)VALUES("https://www.retinalatina.org/");
INSERT INTO enlaces(URL)VALUES("https://www.youtube.com/");
INSERT INTO enlaces(URL)VALUES("https://tv.apple.com/es?l=es");

INSERT INTO usuario(nickname,contrasenia,email)VALUES("","","");