CREATE TABLE Enlaces(
idEnlaces INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
URL VARCHAR(500) NOT NULL
);

CREATE TABLE Item(
idItem INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR(100) NOT NULL,
contenido VARCHAR(500) NOT NULL,
portada VARCHAR(500) NOT NULL,
tipo VARCHAR(100) NOT NULL,
trailer VARCHAR(500) NOT NULL,
año INTEGER NOT NULL,
fkEnlaces INTEGER NOT NULL,
CONSTRAINT FOREIGN KEY (fkEnlaces) REFERENCES Enlaces(idEnlaces)
);

CREATE TABLE Usuario(
idUsuario INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
nickname VARCHAR(100) NOT NULL,
contrasenia VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL
);

CREATE TABLE Comentarios(
idComentarios INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
cuerpo VARCHAR(500) NOT NULL,
fecha DATE NOT NULL,
puntuacion INTEGER NOT NULL,
fkUsuario INTEGER NOT NULL,
CONSTRAINT FOREIGN KEY (fkUsuario) REFERENCES Usuario(idUsuario),
fkItem INTEGER NOT NULL,
CONSTRAINT FOREIGN KEY (fkItem) REFERENCES Item(idItem)
);